"""Add index on user_id in passwords table

Revision ID: 13359c5aaa9c
Revises: a95ca0e120a8
Create Date: 2024-12-05 18:15:18.199331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13359c5aaa9c'
down_revision: Union[str, None] = 'a95ca0e120a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_passwords_user_id'), 'passwords', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_passwords_user_id'), table_name='passwords')
    # ### end Alembic commands ###
